-- E-Commerce Sales Analysis Project

USE ecommerce;

-- Check available tables in the database
SHOW TABLES;

-- View all records from the dataset
SELECT * FROM ecommerce_10k;


-- Calculate total revenue generated
SELECT SUM(price) AS total_revenue
FROM ecommerce_10k;


-- Find the top 5 products by quantity sold
SELECT product,
       SUM(quantity) AS total_quantity
FROM ecommerce_10k
GROUP BY product
ORDER BY total_quantity DESC
LIMIT 5;


-- Find the top 5 cities with the highest sales
SELECT city,
       SUM(price) AS total_sales
FROM ecommerce_10k
GROUP BY city
ORDER BY total_sales DESC
LIMIT 5;


-- Calculate profit generated by each category
SELECT category,
       SUM(profit) AS total_profit
FROM ecommerce_10k
GROUP BY category
ORDER BY total_profit DESC;


-- Find the most frequently used payment method
SELECT payment_mode,
       COUNT(*) AS total_orders
FROM ecommerce_10k
GROUP BY payment_mode
ORDER BY total_orders DESC;


-- Calculate average customer rating by city
SELECT city,
       AVG(rating) AS average_rating
FROM ecommerce_10k
GROUP BY city
ORDER BY average_rating DESC
LIMIT 5;


-- Count cancelled orders in each city
SELECT city,
       COUNT(*) AS cancelled_orders
FROM ecommerce_10k
WHERE order_status = 'Cancelled'
GROUP BY city
ORDER BY cancelled_orders DESC;


-- Calculate sales for each month
SELECT MONTH(order_date) AS month,
       SUM(price) AS monthly_sales
FROM ecommerce_10k
GROUP BY month
ORDER BY monthly_sales DESC
LIMIT 5;


-- Find the top 10 products generating the highest profit
SELECT product,
       SUM(profit) AS total_profit
FROM ecommerce_10k
GROUP BY product
ORDER BY total_profit DESC
LIMIT 10;


-- Calculate average delivery time
SELECT AVG(delivery_days) AS avg_delivery_days
FROM ecommerce_10k;


-- Find customers who spent the most money
SELECT customer_name,
       SUM(price) AS total_spent
FROM ecommerce_10k
GROUP BY customer_name
ORDER BY total_spent DESC
LIMIT 10;


-- Analyze sales based on discount percentage
SELECT discount,
       SUM(price) AS sales
FROM ecommerce_10k
GROUP BY discount
ORDER BY sales;

